
package it.beije.ws.jaxws.contacts.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Contacts", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Contacts {


    /**
     * 
     * @return
     *     returns java.util.List<it.beije.ws.jaxws.contacts.client.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContacts", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.ws.jaxws.contacts.client.GetContacts")
    @ResponseWrapper(localName = "getContactsResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.ws.jaxws.contacts.client.GetContactsResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsResponse")
    public List<Contact> getContacts();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNames", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.ws.jaxws.contacts.client.GetNames")
    @ResponseWrapper(localName = "getNamesResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.ws.jaxws.contacts.client.GetNamesResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesResponse")
    public List<String> getNames();

}
