
package it.beije.ws.jaxws.contacts.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Contacts", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Contacts {


    /**
     * 
     * @return
     *     returns it.beije.ws.jaxws.contacts.client.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesResponse")
    public StringArray getNames();

    /**
     * 
     * @return
     *     returns it.beije.ws.jaxws.contacts.client.ContactArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsResponse")
    public ContactArray getContacts();

}
